name: "Rhasspy Junior"
description: "Simplified voice control for Home Assistant"
version: "0.2.2"
url: "https://github.com/rhasspy/rhasspy-junior"
slug: "rhasspy_junior"
init: false
arch:
  - aarch64
  - amd64
audio: true
homeassistant_api: true
map:
  - "share:rw"
