---
version: 1.0.1
slug: porcupine1
name: porcupine1
description: porcupine1 using the Wyoming protocol
url: https://github.com/rhasspy/hassio-addons/tree/master/porcupine1
arch:
  - amd64
  - aarch64
  - armv7
init: false
discovery:
  - wyoming
options:
  sensitivity: 0.5
  debug_logging: false
schema:
  sensitivity: float
  debug_logging: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
