---
version: 1.1.0
slug: whisper.cpp
name: whisper.cpp
description: whisper.cpp using the Wyoming protocol
url: https://github.com/rhasspy/hassio-addons/tree/master/whisper.cpp
arch:
  - amd64
  - aarch64
  - armv7
init: false
discovery:
  - wyoming
backup_exclude:
  - "*.bin"
map:
  - share:rw
options:
  model: tiny.en-q5_1
  language: en
  beam_size: 5
  audio_context_base: 300
  debug_logging: false
schema:
  model: |
    list(tiny|tiny.en|tiny-q5_1|tiny.en-q5_1|base|base.en|base-q5_1|base.en-q5_1|small|small.en|small-q5_1|small.en-q5_1|medium|medium.en|medium-q5_0|medium.en-q5_0|large-v1|large-v2|large-v2-q5_0|large-v3|large-v3-q5_0)
  language: |
    list(auto|en|zh|de|es|ru|ko|fr|ja|pt|tr|pl|ca|nl|ar|sv|it|id|hi|fi|vi|he|uk|el|ms|cs|ro|da|hu|ta|no|th|ur|hr|bg|lt|la|mi|ml|cy|sk|te|fa|lv|bn|sr|az|sl|kn|et|mk|br|eu|is|hy|ne|mn|bs|kk|sq|sw|gl|mr|pa|si|km|sn|yo|so|af|oc|ka|be|tg|sd|gu|am|yi|lo|uz|fo|ht|ps|tk|nn|mt|sa|lb|my|bo|tl|mg|as|tt|haw|ln|ha|ba|jw|su|yue)
  beam_size: int
  audio_context_base: int
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.9.0
